#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0 AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /src
COPY ["OCMS.Api.Core/OCMS.Api.Core.csproj", "OCMS.Api.Core/"]
RUN dotnet restore "OCMS.Api.Core/OCMS.Api.Core.csproj"
COPY . .
WORKDIR "/src/OCMS.Api.Core"
RUN dotnet build "OCMS.Api.Core.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "OCMS.Api.Core.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "OCMS.Api.Core.dll"]